# -*- coding: utf-8 -*-
"""Gen AI Intro session

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10w26D14ziunjeiE-H7hFQjebIibezfqI
"""

#  write a python code to find the square root of given number from user
import math

num_str = input("Enter a number: ")
num = float(num_str)
square_root = math.sqrt(num)
print(f"The square root of {num} is {square_root}")

# write a python program to swap two variables (short and simple)

a = input("a: ")
b = input("b: ")

print(f"Before swapping: a = {a}, b = {b}")

a, b = b, a
print(f"After swapping: a = {a}, b = {b}")

# write a python program to check wether the give number is positive,negative or zero

num = float(input("Enter a number: "))

if num > 0:
  print("The number is positive.")
elif num < 0:
  print("The number is negative.")
else:
  print("The number is zero.")

# write a python program to find the given number is even or odd

num = int(input("Enter an integer: "))

if num % 2 == 0:
  print("even number")
else:
  print("odd number")

# write a python program to find the factorial of a given number enter by the user

# write a python program to find the factorial of a given number enter by the user

import math

num = int(input("Enter a non-negative integer: "))

if num < 0:
  print("Factorial is not defined for negative numbers.")
elif num == 0:
  print("The factorial of 0 is 1.")
else:
  factorial = math.factorial(num)
  print(f"The factorial of {num} is {factorial}")

# write a python program to find the palindrome of a given number enter by the user

num_str = input("Enter a number or string: ")

if num_str == num_str[::-1]:
  print(f"{num_str} is a palindrome.")
else:
  print(f"{num_str} is not a palindrome.")

# write a python program to create data with three features name,age,city and display the name, age, and city of those greater than 25

data = [
    {"name": "Alice", "age": 30, "city": "New York"},
    {"name": "Bob", "age": 22, "city": "Los Angeles"},
    {"name": "Charlie", "age": 35, "city": "Chicago"},
    {"name": "David", "age": 28, "city": "Houston"},
    {"name": "Eve", "age": 20, "city": "Miami"}
]

print(data)

print("Individuals older than 25:")
for person in data:
  if person["age"] > 25:
    print(f"Name: {person['name']}, Age: {person['age']}, City: {person['city']}")

# write a python program to design 3 input AND gate implementation

def and_gate_3input(a, b, c):
  """Implements a 3-input AND gate."""
  if a == 1 and b == 1 and c == 1:
    return 1
  else:
    return 0

# Test cases
print(f"AND(0, 0, 0): {and_gate_3input(0, 0, 0)}")
print(f"AND(0, 0, 1): {and_gate_3input(0, 0, 1)}")
print(f"AND(0, 1, 0): {and_gate_3input(0, 1, 0)}")
print(f"AND(0, 1, 1): {and_gate_3input(0, 1, 1)}")
print(f"AND(1, 0, 0): {and_gate_3input(1, 0, 0)}")
print(f"AND(1, 0, 1): {and_gate_3input(1, 0, 1)}")
print(f"AND(1, 1, 0): {and_gate_3input(1, 1, 0)}")
print(f"AND(1, 1, 1): {and_gate_3input(1, 1, 1)}")